meetingmatters/meetings/urls.py
from django.conf.urls.defaults import patterns, include, url

from . import feeds
from . import views

urlpatterns = patterns('meetings',
    # Create
    url(r'^create/$', views.CheckForSimilarMeetingsView.as_view(),
    	name='create_meeting_search_similar'),
    url(r'^create/step2$', views.CreateMeetingInfoView.as_view(),
    	name='create_meeting_fill_info'),
    url(r'^venue/create/$', views.CreateVenueInfoView.as_view(),
      name='meetings_create_venue'),

    # Browse
    url(r'^$', views.MeetingListView.as_view(),
        name='browse_meetings_meeting_list'),
    url(r'^listpartial$', views.MeetingListPartialView.as_view(),
        name='browse_meetings_meeting_list_partial'),
    url(r'^~(?P<slug>[^/]+)/$', views.MeetingDetailView.as_view(),
        name='browse_meetings_meeting_detail'),

    # Update
    url(r'^(?P<slug>.+)/edit/$', views.UpdateMeetingInfoView.as_view(),
        name='update_meeting_fill_info'),

    # Feeds
    url(r'^rss/$', feeds.MeetingListRss(),
        name='meeting_list_rss'),
    url(r'^ical/$', feeds.MeetingListICal(),
        name='meeting_list_ical'),

    # API
    url(r'^api/v1/meetings/$', views.MeetingListApiView.as_view(),
        name='meeting_list_resource')
)

meetingmatters/utils/urls.py
from django.conf.urls.defaults import patterns, include, url

from . import views

urlpatterns = patterns('utils',
    # Geo
    url(r'^geoautocomplete/$', views.GeoAutocomplete.as_view(),
    	name='utils_geoautocomplete'),
)

meetingmatters/meetings/models.py
from __future__ import division
#from django.contrib.gis.db import models
from django.contrib.gis.db import models
from django.contrib.gis import geos
from django.core.cache import cache
from taggit.managers import TaggableManager
from taggit.models import TaggedItemBase

from ..utils.geocode import geocode
from ..utils.models import TimestampedModelMixin, SlugifiedModelMixin


class CachingManager (models.Manager):
    def get_cache_key(self):
        opts = self.model._meta
        return '.'.join([opts.app_label, opts.module_name])

    def cached(self):
        key = self.get_cache_key()
        topics = cache.get(key)

        if topics is None:
            topics = self.all()
            cache.set(key, topics)

        return topics

    def bust_cache(self):
        key = self.get_cache_key()
        cache.delete(key)


class Venue (SlugifiedModelMixin, TimestampedModelMixin, models.Model):
    """A venue where meetings take place"""

    name = models.CharField(max_length=256, null=True, blank=True)
    """The name of the venue"""

    address = models.CharField(max_length=1024)
    """The address of the venue"""

    location = models.PointField(blank=True)
    """A geographical point representing the venue"""

    objects = models.GeoManager()

    def get_pre_slug(self):
        return self.name or self.address

    def __unicode__(self):
        if self.name:
            return "{n}, {a}".format(n=self.name, a=self.address)
        else:
            return self.address

    objects = CachingManager()

    def save(self, *args, **kwargs):
        if self.location is None:
            geo = geocode(self.address)
            if not geo or not geo['results']:
                raise models.FieldError('Cannot find address')
            geo = geo['results'][0]
            self.location = geos.Point(
                geo['geometry']['location']['lng'],
                geo['geometry']['location']['lat'])
        super(Venue, self).save(*args, **kwargs)


class MeetingTopicManager (CachingManager):
    def all(self):
        return super(MeetingTopicManager, self).all().order_by('name')


class MeetingTopic (SlugifiedModelMixin, models.Model):
    name = models.CharField(verbose_name='Topic', max_length=100)

    # meetings (reverse)

    objects = CachingManager()
    ordered_objects = MeetingTopicManager()

    def __unicode__(self):
        return self.name

    def get_pre_slug(self):
        return self.name

    def save(self, *args, **kwargs):
        super(MeetingTopic, self).save(*args, **kwargs)
        MeetingTopic.objects.bust_cache()


class Meeting (SlugifiedModelMixin, TimestampedModelMixin, models.Model):
    title = models.CharField(max_length=1023, verbose_name="Meeting Name", help_text="The meeting name should be descriptive. What makes a good meeting name? What makes a bad one?")
    """The title of the meeting"""

    description = models.TextField(null=True, blank=True, help_text="Give readers an idea of the purpose of the meeting, as well as what will be discussed. If there is an agenda, include that as well.")
    """The meeting description, potentially including the agenda."""

    begin_time = models.DateTimeField(null=True, blank=True, verbose_name="Start time")
    """When does the meeting start.  NULL means TBD."""

    end_time = models.DateTimeField(null=True, blank=True, verbose_name="End time")
    """When does the meeting end.  NULL means ???."""

    venue = models.ForeignKey('Venue', null=True, blank=True, related_name='meetings')
    """The venue where the meeting will take place"""

    venue_name = models.TextField(null=True, blank=True, verbose_name="Venue Address")
    """The name or address of the venue.  NULL means TBD."""

#    venue_location = models.PointField(null=True, blank=True)
#    """The geographical location of the venue.  NULL means TBD."""

    venue_additional = models.TextField(null=True, blank=True, verbose_name="Notes")
    """Additional information about the venue, such as room number."""

    tags = models.ManyToManyField('MeetingTopic', related_name='meetings', blank=True, verbose_name="Topics", help_text="A comma-separated list of topics that will be discussed at the meeting.")
    """The tags for the meeting"""

    speakers = models.ManyToManyField('auth.User', related_name='speaking_meetings', blank=True)
    attendees = models.ManyToManyField('auth.User', related_name='attending_meetings', blank=True)
    """Who is attending and/or speaking at the meeting"""

    canceled = models.BooleanField(default=False, blank=True)
    """Whether the meeting is canceled"""

    # Meeting has no geo fields, but we want to be able to do geo queries on
    # meetings, so we need a GeoManager.
    objects = models.GeoManager()

    def __unicode__(self):
        return self.title

    @models.permalink
    def get_absolute_url(self):
        return ('browse_meetings_meeting_detail', [str(self.slug)])

    def get_pre_slug(self):
        return self.title

    # It takes "a long time" to get the tags for each meeting in a meeting list,
    # so we're going to do some simple caching.
    def get_cached_tags(self):
        if self.pk is None:
            return []

        cache_key = 'tags_' + str(self.pk)
        tags = cache.get(cache_key)
        if tags is None:
            tags = self.tags.all()
            cache.set(cache_key, tags)

        return tags

    def bust_tag_cache(self):
        cache_key = 'tags_' + str(self.pk)
        cache.delete(cache_key)

    def similar_meetings(self, threshold=0.7):
        T = set(self.title.lower())
        all_meetings = Meeting.objects.all()

        similar_meetings = []
        for meeting in all_meetings:
            S = set(meeting.title.lower())
            similarity = len(S & T) / len(S | T)
            if similarity > threshold:
                similar_meetings.append(meeting)

        return similar_meetings

meetingmatters/meetings/forms.py
import datetime
import floppyforms as forms
import taggit.forms
import taggit.models
from django.contrib.gis import geos
from django.core.urlresolvers import reverse
from uni_form.helper import FormHelper
from uni_form.layout import Layout, ButtonHolder, Submit, Fieldset

from . import models
from ..utils.geocode import geocode

import logging
log = logging.getLogger(__name__)

class CheckForSimilarMeetingsForm (forms.Form):
    title = forms.CharField(
        label="Meeting Name",
        help_text="The meeting name should be descriptive. What makes a good meeting name? What makes a bad one?",
        widget=forms.TextInput(attrs={'class':'span6'})
    )
    begin_time = forms.SplitDateTimeField(
        label="Start time",
        input_time_formats=('%H:%M', '%I:%M %p'),
        required=False
    )
    end_time = forms.SplitDateTimeField(
        label="End time",
        input_time_formats=('%H:%M', '%I:%M %p'),
        required=False
    )

    def __init__(self, *args, **kwargs):

        self.helper = FormHelper()
        self.helper.form_class = 'form-horizontal'

        self.helper.layout = Layout(
            Fieldset(
                'Step 0: Check whether meeting exists',
                'title', 'begin_time', 'end_time',
            ),
            ButtonHolder(
                Submit('check', 'Continue', css_class='btn btn-primary pull-right')
            )
        )
        return super(CheckForSimilarMeetingsForm, self).__init__(*args, **kwargs)


#
# We won't use the taggit tags, but the form fields are still useful.
#
from django.utils.translation import ugettext as _
from taggit.utils import parse_tags, edit_string_for_tags

class MeetingTopicWidget(forms.TextInput):
    def render(self, name, value, attrs=None):
        if value is not None and not isinstance(value, basestring):
            value = edit_string_for_tags(models.MeetingTopic.objects.filter(id__in=value))
        return super(MeetingTopicWidget, self).render(name, value, attrs)


class MeetingTopicField(forms.CharField):
    widget = MeetingTopicWidget

    def clean(self, value):
        value = super(MeetingTopicField, self).clean(value)
        try:
            tag_names = parse_tags(value)
        except ValueError:
            raise forms.ValidationError(_("Please provide a comma-separated list of tags."))

        tags = []
        for tag_name in tag_names:
            tag, created = models.MeetingTopic.objects.get_or_create(name=tag_name)
            tags.append(tag.id)

        return tags


class DatepickerInput (forms.DateInput):
    template_name = 'floppyforms/meetings_datepicker.html'


class GeoBBInput (forms.DateInput):
    template_name = 'floppyforms/meetings_bbmap_google.html'


class CancelMeetingInput (forms.CheckboxInput):
    template_name = 'floppyforms/meetings_cancel_box.html'


class FillInMeetingInfoForm (forms.ModelForm):
    begin_time = forms.SplitDateTimeField(
        label="Start time",
        input_time_formats=('%H:%M', '%I:%M %p')
    )
    end_time = forms.SplitDateTimeField(
        label="End time",
        input_time_formats=('%H:%M', '%I:%M %p')
    )
    venue = forms.ModelChoiceField(
        queryset=models.Venue.objects.all(),
        widget=forms.Select(attrs={'class':'span4'}),
        required=False,
        help_text='If you do not find the venue in the list, you can <a href="#create-venue-modal" data-toggle="modal">create</a> a new one.'
    )
    tags = MeetingTopicField(
        widget=MeetingTopicWidget(attrs={'class':'span6'}),
    )
#    venue_name = forms.CharField(
#        label="Name",
#        widget=forms.TextInput(attrs={'class':'span6'})
#    )
#    venue_address = forms.CharField(
#        label="Address",
#        widget=forms.TextInput(attrs={'class':'span5'})
#    )

    class Meta:
        model = models.Meeting
        exclude = ('speakers', 'attendees', 'slug', 'venue_name')
        widgets = {
            'title': forms.TextInput(attrs={'class':'span6'}),
            'description': forms.Textarea(attrs={'class':'span6'}),
            'venue': forms.Select(attrs={'class':'span4'}),
            'venue_additional': forms.Textarea(attrs={'class':'span6', 'rows':'3'}),
            'canceled': CancelMeetingInput(),
        }

    def __init__(self, *args, **kwargs):

        self.helper = FormHelper()
        self.helper.form_method = 'POST'
        self.helper.form_action = ''
        self.helper.form_class = 'form-horizontal'

        self.helper.layout = Layout(
            Fieldset(
                'Step 1: Fill in general information',
                'title', 'begin_time', 'end_time',
                'description', 'tags'
            ),
            Fieldset(
                'Step 2: Enter the location',
                'venue', 'venue_additional'
            ),
            Fieldset(
                'Cancellation',
                'canceled'
            ),
            ButtonHolder(
                Submit('check', 'Save', css_class='btn btn-primary pull-right')
            )
        )

#        if instance and instance.venue:
#            initial = initial or {}
#            initial.update({
#                'venue_name': instance.venue.name,
#                'venue_address': instance.venue.address
#            })

#        kwargs.update({'initial': initial, 'instance': instance})
        return super(FillInMeetingInfoForm, self).__init__(*args, **kwargs)

    def save(self, *args, **kwargs):
        instance = super(FillInMeetingInfoForm, self).save(*args, **kwargs)
        instance.bust_tag_cache()
        return instance


class DefaultFilters (forms.Form):
    pass


class MeetingFilters (forms.Form):
    center = forms.CharField(required=False)
    radius = forms.FloatField(required=False)
    bbox = forms.CharField(required=False, widget=GeoBBInput())
    earliest = forms.DateField(required=False, initial=datetime.date.today, widget=DatepickerInput())
    latest = forms.DateField(required=False, widget=DatepickerInput())
    tags = forms.ModelMultipleChoiceField(queryset=models.MeetingTopic.objects.all(), to_field_name='slug', required=False)
    canceled = forms.BooleanField(label='Show canceled meetings', required=False, initial=False)

    def clean(self):
        cleaned_data = super(MeetingFilters, self).clean()
        center = cleaned_data.get('center')
        radius = cleaned_data.get('radius')

        # Center and radius must be set together
        if center and not radius:
            msg = u'Radius is required when center is specified.'
            self._errors['radius'] = self.error_class([msg])

        if radius and not center:
            msg = u'Center is required when radius is specified.'
            self._errors['center'] = self.error_class([msg])

        if center:
            try:
                center = cleaned_data['center'] = geos.fromstr(center)
            except geos.GEOSException:
                msg = u'Center is not a valid WKT point (see http://en.wikipedia.org/wiki/Well-known_text)'
                self._errors['center'] = self.error_class([msg])

        # N, S, E, and W must all be set together, or none at all.
        bbox = cleaned_data.get('bbox')
        if bbox:
            try:
                n, e, s, w = [float(val) for val in cleaned_data['bbox'].split(',')]
                bbox = u'POLYGON(({e} {n}, {e} {s}, {w} {s}, {w} {n}, {e} {n}))'.format(n=n, e=e, s=s, w=w)
            except ValueError:
                msg = u'Bbox must have exactly 4 comma-separated values.'
                self._errors['bbox'] = self.error_class([msg])
            else:
                cleaned_data['bbox'] = geos.fromstr(bbox)

        return cleaned_data


class VenueForm (forms.ModelForm):
    class Meta:
        model = models.Venue
        exclude = ['slug', 'location']

    def __init__(self, *args, **kwargs):
        self.helper = FormHelper()
#        self.helper.form_method = 'POST'
#        self.helper.form_action = ''
#        self.helper.form_class = 'form-horizontal'
        self.helper.form_tag = False

#        self.helper.layout = Layout(
#            Fieldset(
#                'Step 1: Fill in general information',
#                'title', 'begin_time', 'end_time',
#                'description', 'tags'
#            ),
#            Fieldset(
#                'Step 2: Enter the location',
#                'venue', 'venue_additional'
#            ),
#            ButtonHolder(
#                Submit('check', 'Save', css_class='btn btn-primary pull-right')
#            )
#        )

        return super(VenueForm, self).__init__(*args, **kwargs)

    def clean(self, *args, **kwargs):
        cleaned_data = super(VenueForm, self).clean(*args, **kwargs)

        address = cleaned_data.get('address')
        if self.instance.address != address:
            geo = geocode(address)

            if not geo or not geo['results']:
                raise forms.ValidationError('Could not find this address.')

            geo = geo['results'][0]
            self.instance.location = geos.Point(
                geo['geometry']['location']['lng'],
                geo['geometry']['location']['lat'])

        return cleaned_data

meetingmatters/meetings/views/api.py
from rest_framework.generics import ListAPIView
from .. import serializers
from .. import models

class MeetingListApiView (ListAPIView):
    model = models.Meeting
    serializer_class = serializers.MeetingSerializer
    paginate_by = 10
    paginate_by_param = 'page_size'

meetingmatters/meetings/templates/browse_meetings-meeting_detail.html
{% extends "bootstrap-layout.html" %}
{% load url from future %}
{% load shorturl %}

{% block bootstrap_container_content %}

  <div class="row">
  	<div class="span8">
      <h2>{{ meeting.title }}</h2>

      <div class="row">
        <div class="span4">
          {% if meeting.begin_time %}
            <div class="meeting-time">{{ meeting.begin_time|date:"l, F j, Y" }}</div>
            <div class="meeting-time">
              {{ meeting.begin_time|time:"g:i A" }}
              {% if meeting.end_time %}
                - {{ meeting.end_time|time:"g:i A" }}
              {% endif %}
            </div>
          {% else %}
            <div class="meeting-time">Time TBD</div>
          {% endif %}

        </div>

        <div class="span4" align="right">
          <div>{{ meeting.venue|default:"Location TBD" }}</div>
          <div>{{ meeting.venue_additional|urlizetrunc:36 }}</div>
        </div>
      </div>

      {% if meeting.canceled %}
        <div class="alert alert-error">
          This meeting has been canceled.
        </div>
      {% endif %}

      <div class="meeting-description">
        {{ meeting.description|linebreaks|urlizetrunc:50 }}
      </div>

      <div>
        <a href="{% url 'update_meeting_fill_info' meeting.slug %}">Edit this meeting</a>
      </div>
  	</div>

    <div class="span4">
      <div class="well">
        <h4>Topics</h4>
        <div>
          {% for tag in meeting.get_cached_tags %}
            <a class="meeting-tag btn btn-mini" href="{% url 'browse_meetings_meeting_list' %}?tags={{ tag.slug|urlencode }}">{{ tag.name }} <i class="icon-tag"></i></a>
          {% endfor %}
        </div>

<!--        <hr>-->

<!--        <div class="meeting-share">-->
<!--          <a href="{% shorturl meeting %}"><i class="icon-share"></i> {% shorturl meeting %}</a>-->
<!--        </div>-->

      </div>
    </div>
  </div>

{% endblock %}

meetingmatters/meetings/templates/browse_meetings-meeting_list.html
{% extends "bootstrap-layout.html" %}

{% load url from future %}

{% block bootstrap_container_content %}
  <link rel="stylesheet" href="http://leaflet.cloudmade.com/dist/leaflet.css">
  <!--[if lte IE 8]><link rel="stylesheet" href="http://leaflet.cloudmade.com/dist/leaflet.ie.css"><![endif]-->

  <script src="http://leaflet.cloudmade.com/dist/leaflet.js"></script>
  <script src="{{ STATIC_URL }}js/meetings_filter.js"></script>
  <script src="{{ STATIC_URL }}js/meetings_subscription.js"></script>

  <div class="row">
    <div id="id_browse-meetings-wrapper" class="browse-meetings-wrapper span8">
      {% include "partials/meetings_browse_meetings.html" %}
    </div>

    <div class="homepage-sidebar-wrapper span4">
      <div class="well">

        {% if filter_form.is_valid %}
        {% with filters=filter_form.cleaned_data %}
        <form method="GET" id="id_filter_form">
          <div id="id_update-filters-wrapper">
            <button id="id_update-filters-btn" class="btn btn-primary btn-large" type="submit">Update Filters</button>
            <hr class="filter-section-separator">
          </div>

          <h4 id="id_place-filter-header">Place</h4>
          <div id="id_place-filter-wrapper">
            {{ filter_form.bbox }}
          </div>

          <hr class="filter-section-separator">

          <h4 id="id_time-filter-header">Time</h4>
          <div id="id_time-filter-wrapper">
            <div class="filter-date-wrapper">
              <label for="id_earliest">From</label>
              {{ filter_form.earliest }}
            </div>

            <div class="filter-date-wrapper">
              <label for="id_latest">Until</label>
              {{ filter_form.latest }}
            </div>
          </div>

          <hr class="filter-section-separator">

          <h4 id="id_topics-filter-header">Topics</h4>
          <div id="id_topics-filter-wrapper">
            <ul class="nav nav-pills nav-stacked">
              <li id="id_all_tags-li" {% if not filters.tags %}class="active"{% endif %}>
                <a id="id_all_tags-btn">All</a>
                <script>
                  $(document).ready(function() {
                    initAllTopicsFilter();
                  });
                </script>
                <hr>
              </li>

              {% with selected_tags=filters.tags %}
              {% for tag in tags %}
                <li id="id_tags-{{ tag.slug }}-li"{% if tag in selected_tags %} class="active"{% endif %}>
                  <a id="id_tags-{{ tag.slug }}-btn">{{ tag.name }}</a>
                  <input type="checkbox" name="tags" value="{{ tag.slug }}" id="id_tags-{{ tag.slug }}"{% if tag in selected_tags %} checked="checked"{% endif %} style="display: none">
                  <script>
                    $(document).ready(function() {
                      initTopicFilter('{{ tag.slug }}');
                    });
                  </script>
                </li>
              {% endfor %}
              {% endwith %}
            </ul>
          </div>
        </form>

        <script>
          $(document).ready(function() {
            $('#id_place-filter-header').click(function() {
              togglePlaceFilterVisibility();
            });
            $('#id_time-filter-header').click(function() {
              toggleTimeFilterVisibility();
            });
            $('#id_topics-filter-header').click(function() {
              toggleTopicsFilterVisibility();
            });

            {% if not filters.bbox %}
            hidePlaceFilter();
            {% endif %}

            {% if not filters.earliest and not filters.latest %}
            hideTimeFilter();
            {% endif %}

//            $('#id_topics-filter-wrapper').hide();

            $('#id_filter_form').attr('action', '{% url "browse_meetings_meeting_list_partial" %}');
            $('#id_filter_form').ajaxForm({
              target: '#id_browse-meetings-wrapper'
            });

            var filterTimeout;

            $('#id_filter_form input, #id_filter_form select')
              .not('#id_bbox-jump-to')
              .not('#id_bbox-enable')
              .change(function(e) {
                filterTimeout = updateMeetingList(filterTimeout);
              });

            // If we can do javascript, then there's no need for the Update
            // Filters button.
            $('#id_update-filters-wrapper').remove();
          });
        </script>
        {% endwith %}

        {% else %}
            {{ filter_form.errors }}
        {% endif %} {# filter_form.is_valid #}
      </div>
    </div>
  </div>



{% endblock %}

meetingmatters/meetings/templates/create_meeting-search_similar.html
{% extends "bootstrap-layout.html" %}
{% load uni_form_tags %}

{% block bootstrap_container_content %}

    <div class="row">
      <div class="span8">

        {% uni_form form form.helper %}

      </div>

      <script>
        // By default, set the end date to the same as the begin date.
        $('#id_begin_time_0').change(function() {
          var begin_date = $('#id_begin_time_0').val(),
              end_date = $('#id_end_time_0').val();

          if (end_date === '') {
            $('#id_end_time_0').val(begin_date);
          }
        });
      </script>

      <div class="span4">
        {% if similar_meetings %}
          <div class="alert alert-info">
            <p>We've found the following meetings that seem similar to yours.  Consider modifying or attending one of these instead.</p>

            {% for meeting in similar_meetings %}
              <h5><a href="{% url browse_meetings_meeting_detail meeting.slug %}">{{ meeting.title }}</a></h5>
              {% if meeting.begin_time %}
                <h6>{{ meeting.begin_time|date:"l, F j, Y" }}</h6>
                <h6>{{ meeting.begin_time|time:"g:i A" }}
                    {% if meeting.end_time %}
                      - {{ meeting.end_time|time:"g:i A" }}
                    {% endif %}</h6>
              {% else %}
                <h6>Time TBD</h6>
              {% endif %}

              <hr>
            {% endfor %}

            <p>Does your event appear above?</p>
          </div>
        {% else %}
          <div class="well">
            <p>Enter the name and time of the meeting.  Before creating the meeting, we will search to see whether there are any similar meetings that already exist.</p>
          </div>
        {% endif %}
      </div>
    </div> <!-- row -->

{% endblock %}

meetingmatters/meetings/templates/edit_meeting-fill_info.html
{% extends "bootstrap-layout.html" %}
{% load uni_form_tags %}

{% block bootstrap_container_content %}

    <div class="row">
      <div class="span8">
        {% uni_form form form.helper %}
      </div>
    </div> <!-- row -->

  <div class="modal hide fade" id="create-venue-modal">
    <form class="form-horizontal" method="POST" action="{% url meetings_create_venue %}">
      <div class="modal-header">
        <a class="close" data-dismiss="modal">×</a>
        <h3>Create a venue</h3>
      </div>
      <div class="modal-body" id="venue-form-wrapper">
        {% uni_form venue_form venue_form.helper %}
      </div>
      <div class="modal-footer">
        <a class="btn" data-dismiss="modal">Close</a>
        <button type="submit" class="btn btn-primary">Save venue</a>
      </div>
    </form>
  </div>

  <script>
    $(document).ready(function() {
        $('#create-venue-modal form').ajaxForm(function(responseText, statusText, xhr, $form) {
          if (xhr.status === 201) {
            $('#create-venue-modal').modal('hide');
            venue = $.parseJSON(xhr.responseText)
            venueData[venue.pk] = venue

            $newOption = $('<option value="' + venue.pk +'" selected="selected">' + venue.name + '</option>');
            $('#id_venue').append($newOption);
            initVenueField();
            fillVenueData();
          } else {
            $('#venue-form-wrapper').html(responseText)
          }
        });
    });
  </script>

{% endblock %}